# Generated by Django 6.0.6 on 2026-06-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
