# Generated by Django 6.0.6 on 2026-06-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_address_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="line2",
        ),
    ]
