# Generated by Django 6.0.6 on 2026-06-24 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("product_description", models.TextField(blank=True, null=True)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                (
                    "product_color_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_color_hex_code",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("product_size", models.IntegerField(blank=True, null=True)),
                ("product_is_available", models.BooleanField(default=True)),
                (
                    "product_created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("product_updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "second_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("second_description", models.TextField(blank=True, null=True)),
                ("technical_details", models.JSONField(blank=True, null=True)),
                ("is_new_arrival", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RUNNING", "Running"),
                            ("CASUAL", "Casual"),
                            ("FORMAL", "Formal"),
                            ("SPORTS", "Sports"),
                            ("BOOTS", "Boots"),
                            ("SANDALS", "Sandals"),
                            ("SLIPPERS", "Slippers"),
                        ],
                        default="CASUAL",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("KIDS", "Kids"),
                            ("UNISEX", "Unisex"),
                        ],
                        default="UNISEX",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
