# Generated by Django 6.0.6 on 2026-06-24 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_new_arrival",
            new_name="is_new",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_is_available",
            new_name="product_available",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="second_description",
            new_name="secondary_description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="second_title",
            new_name="secondary_title",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_color_hex_code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_color_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="technical_details",
        ),
        migrations.AddField(
            model_name="product",
            name="product_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_color_hex",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_available",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="technical_specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Running", "Running"),
                    ("Casual", "Casual"),
                    ("Formal", "Formal"),
                    ("Sports", "Sports"),
                    ("Boots", "Boots"),
                    ("Sandals", "Sandals"),
                    ("Slippers", "Slippers"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Kids", "Kids"),
                    ("Unisex", "Unisex"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=50)),
                (
                    "color_hex",
                    models.CharField(
                        help_text="HEX color code, e.g., #D84200", max_length=50
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="product.productcolor",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("5", "5"),
                            ("5.5", "5.5"),
                            ("6", "6"),
                            ("6.5", "6.5"),
                            ("7", "7"),
                            ("7.5", "7.5"),
                            ("8", "8"),
                            ("8.5", "8.5"),
                            ("9", "9"),
                            ("9.5", "9.5"),
                            ("10", "10"),
                            ("10.5", "10.5"),
                            ("11", "11"),
                            ("11.5", "11.5"),
                            ("12", "12"),
                            ("12.5", "12.5"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=10,
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specification", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
