# Generated by Django 6.0.6 on 2026-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_is_new_arrival_product_is_new_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size_available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="technical_specification",
        ),
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.CharField(
                choices=[
                    ("5", "5"),
                    ("5.5", "5.5"),
                    ("6", "6"),
                    ("6.5", "6.5"),
                    ("7", "7"),
                    ("7.5", "7.5"),
                    ("8", "8"),
                    ("8.5", "8.5"),
                    ("9", "9"),
                    ("9.5", "9.5"),
                    ("10", "10"),
                    ("10.5", "10.5"),
                    ("11", "11"),
                    ("11.5", "11.5"),
                    ("12", "12"),
                    ("12.5", "12.5"),
                    ("13", "13"),
                    ("14", "14category"),
                    ("15", "15"),
                ],
                max_length=10,
            ),
        ),
    ]
