# Generated by Django 6.0.6 on 2026-06-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_product_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_image",
        ),
    ]
